# Generated by Django 4.2.2 on 2023-06-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=300, verbose_name='Titulo')),
                ('edicion', models.CharField(default='', max_length=300, verbose_name='Edicion')),
                ('editorial', models.CharField(default='', max_length=300, verbose_name='Editorial')),
                ('anio_de_publicacion', models.IntegerField(default=0, verbose_name='Año de publicacion')),
                ('pagina', models.IntegerField(default=0, verbose_name='No. de Paginas')),
            ],
        ),
    ]
