# Generated by Django 4.2.2 on 2023-06-16 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='pagina',
            new_name='paginas',
        ),
    ]
